version: '3.3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '5442:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=info
    volumes:
      - app-db-data:/data/postgres
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - db
volumes:
  app-db-data:
  app:
